//
// Created by Moxiao Li on 4/5/26.
//

#ifndef ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_NAIVE_H
#define ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_NAIVE_H
void run_profile_mm_naive() ;
#endif //ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_NAIVE_H