//
// Created by Moxiao Li on 4/5/26.
//

#ifndef ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_TRANSPOSED_H
#define ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_TRANSPOSED_H
void run_profile_mm_transposed();
#endif //ADVANCED_COMPUTING_FOR_FINANCE_PROFILE_MM_TRANSPOSED_H